### ISSUE TITLE
Make clicking on an item after searching for it add it to the diary instead of opening the edit menu

### ISSUE THREAD

**Issue by PopeRigby** [davidhealey/waistline#128]
Intended behavior: clicking on an item after you search for it adds it to your diary

Current behavior: clicking on an item after you search for it opens up the menu to edit the nutrition details

**Comment by davidhealey** [comment]
This is intentional to allow you to check that the data retrieved from Open Food Facts is correct for the product you have in your hand. But I can see how your way also makes sense and then if it's not right you could edit it afterwards, so I'll consider changing this.

**Comment by davidhealey** [comment]
I've come up with a solution. 

When you search the results will be displayed in a list with a checkbox for each one. If you check one or more items and press the tick then those items will be added to both your internal food list and to the diary. 

If you click on the item name (instead of checking the box) you'll be taken to the item editor as is the current behaviour.

This new setup also means it's possible to add multiple search results at once.
