### ISSUE TITLE
Add a dark UI

### ISSUE THREAD

**Issue by gappleto97** [davidhealey/waistline#17]
It would be nice to have both a night theme, and an AMOLED theme. The latter should have pure black elements in many places, since these use less energy.

**Comment by davidhealey** [comment]
Do you know how to write CSS? What's an AMOLED theme?

**Comment by davidhealey** [comment]
Excellent!

**Comment by maste9** [comment]
To keep you updated:

WIP! I managed to implement a theme selector in settings page and will offer a basic night and an amoled theme as soon as I managed both the change of theme from storage as well as on change of selector to work on same time 😁

Unfortunately my code refuses to do so yet but I'm hopeful that I will solve this the next few days. I'll then send you a PR.

**Comment by davidhealey** [comment]
I merged your branch into the master. I did a little refactoring and I fixed a typo that was causing the issue with saving the selection. You where saving the .prop() instead of the .val(). Please try out the latest master and if all is good I think I'll make a new release for F-Droid and Play and we can close this issue. Thanks again for your work, add your name/website to the CSS files if you like :)

**Comment by maste9** [comment]
Could at least test it on browser and it works fine! :+1:  If it's running on your android test device too I would say that's ready for release. I will add my nick and my own gitea-site when I have time to fiddle around with the themes further.
I'm a bit proud, I must say, as this is my first official pull request to a project that's not mine. From this point of view it was a wonderful decision of yours to choose cordova and not native java to me ^^
Thanks for feedback by the way. Best way to learn and advance in sw development.

**Comment by davidhealey** [comment]
I'm glad you were able to find your way around the code easily :) when I get to the "theme" stage of my Kotlin version I'll be taking the info straight from your CSS!
