### ISSUE TITLE
[Feature request] Make quick add "title" editable

### ISSUE THREAD

**Issue by serpico** [davidhealey/waistline#174]
Currently when we quickly input a calories number it appears as "_Calories - NaN Quick Add_"

![Screenshot_2019-07-06-05-59-20](https://user-images.githubusercontent.com/1227077/60751363-eadfab00-9fb3-11e9-9a31-1ba7adc703f0.png)

it'd be sweet if we could edit ( maybe in the view below ) this to remember what we ate.

![Screenshot_2019-07-06-05-59-36](https://user-images.githubusercontent.com/1227077/60751386-1498d200-9fb4-11e9-9609-23b67d6eebaf.png)

**Comment by davidhealey** [comment]
Yeah that bug's already been fixed in the develop branch and will be available in the next release :)

**Comment by serpico** [comment]
Thanks @davidhealey , not to rush you or anything :) but any idea when the next release gonna hit F-droid? Is the develop branch version available through Google Store ( beta version ) or...?

**Comment by davidhealey** [comment]
Hi,

The develop branch is what I would call pre-alpha. It's contains large rewrites of some major parts of the app. My goal with that branch is to make the app less laggy. So I completely removed jquery and had to rewrite all the parts that relied on that library in vanilla JS. I'm still using Onsen for the UI but it's buggy and I still feel it has lag, so I'm probably going to move to Framework7 so that will add extra time....

There is a debug build APK available in one of the other GitHub issues, so if you want to use the develop version you'll have to search for it. But it's missing features like stats, and it is full of bugs. I'm using it daily at the moment but I wouldn't recommend it to anyone.

If any major show stopping bugs are reported with the current release version I'll do my best to fix those on the Master branch and push a release, but I haven't seen any reported.
