### ISSUE TITLE
Search only searches local DB

### ISSUE THREAD

**Issue by kevinkoster** [davidhealey/waistline#192]
#86 mentions searching the OFF database from the search box, but I get "Alert - No matching results" for everything that is not in my local DB. Am I missing something? 

PS: Thanks a lot for creating this app! I was thinking of building something similar myself. My vision was to use OFF to obtain nutrition info, the option to create meals from individual foods and implement a barcode scanner, so I was amazed to find that your app does exactly this!

**Comment by davidhealey** [comment]
Hi,
Which version of the App are you using? You may have to set your country in the settings. Other than that the search box will search the OFF database when you are connected to the internet. If you are getting the no matching results message it could be because there are no results for the thing you are searching for in the OFF database. You can test it by searching for it on the OFF website.

**Comment by kevinkoster** [comment]
Hi,
I'm using v2.4.1. Setting the country solved it :) Thanks!
