### ISSUE TITLE
Instructions to build apk (or dev release)

### ISSUE THREAD

**Issue by JPFrancoia** [davidhealey/waistline#249]
Hi,
I've been using waistline for some time now, but I'm really interested in a feature that is only in dev for now. I'm talking about tracking the macros per day (e.g: amount of protein consumed per day, with the target threshold). Sadly I don't know much about Android development and I can't figure a way to build the apk. Could we add some instructions to do so? Or maybe you could build a dev apk? I'd be happy to report bugs.

**Comment by davidhealey** [comment]
Hello,

Adding build instructions isn't a simple process because you need to have Cordova and Android Studio installed and setup correctly which is beyond the scope of a readme. 

You can find more information here - https://cordova.apache.org/docs/en/10.x/guide/cli/

There is a build of the development version available near the bottom of this thread - https://github.com/davidhealey/waistline/issues/217

But be warned you will lose some data that's in your current version (this is why there isn't a new release yet). Also if you installed your current version from the F-Droid store you'll probably need to uninstall it before this dev version will install.
