### ISSUE TITLE
Can't copy/paste into text fields 

### ISSUE THREAD

**Issue by lumbo7332** [davidhealey/waistline#251]
I'm using the latest build from #217. When typing in any text field, I can't long press or use my keyboard actions to copy or paste text. I'm on Android 10, pretty close to stock, on the OnePlus Nord N10 5G.

**Comment by davidhealey** [comment]
Waistline doesn't have a clipboard implementation. However there is a plugin for it that someone (could be me) can implement in the future.
https://www.npmjs.com/package/cordova-clipboard-api

**Comment by davidhealey** [comment]
I've had a look at this and I can't find a solution. The clipboard plugin doesn't seem to be an option because it requires you to manually implement copy/paste controls from what I can tell.

Cordova is actually supposed to have built in copy/paste but I can't get it to work. On my Android phone I can double tap some text in a text entry box which highlights it and I get the option to copy/cut/paste, but if I long tap on another box I don't get any options. However if I enter text into another box and then double tap it I get the same options again and can paste into it. But none of this works on my Android tablet so it seems to be device specific.

If anyone finds a solution please let me know.
