### ISSUE TITLE
Diary page scrolls up by itself after deleting an item

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#260]
After deleting an item from the Diary, the page always scrolls up to the very top of the list by itself. This didn't happen in the previous version of the app and it's pretty annoying.

**Comment by janibonnevier** [comment]
This also happens when editing an item in the Diary.

**Comment by davidhealey** [comment]
This happens because there was a major change in the way the page is updated after an item has been changed.
In the previous version changes happened directly within the dom. In the new (current) version things happen only in the database and the entire page is then reloaded. 

In order to return to the previous behaviour it would require some restructuring, probably not a huge task but not high on my priority list at the moment, although I find it annoying too.
