### ISSUE TITLE
Should use "Add New Item" instead of "Edit Item" when importing from OFF

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#270]
When I scan the barcode of a product that isn't in my local foods database yet, the page displayed says "Edit Item" instead of "Add New Item".

This way I can't tell if the item I scanned is already in the local database or not. Also, since it's using the edit mode, the link button is enabled by default which is a bit annoying when I try to correct some of the information (the values from OFF are not always accurate/up-to-date).

**Comment by davidhealey** [comment]
Done the title - https://github.com/davidhealey/waistline/commit/c40f7a6a49cb04f6f5009344de61da5310be6ea2
Will work on the link button next

**Comment by davidhealey** [comment]
I had another think about the link button for external DB items. Since we're treating them as "new" items to the local DB it makes sense to have the link disabled by default for consistency with adding new items manually.  https://github.com/davidhealey/waistline/commit/6c842fc2cca27bb274bc08e19324ef4dd538acf4
