### ISSUE TITLE
App doesn't fill up the phone screen

### ISSUE THREAD

**Issue by longestmt** [davidhealey/waistline#274]
Just updated to the new version of the app and noticed that the app doesn't fill up my entire screen. 

Device: S21 Ultra 
Version: Android 11

**Comment by longestmt** [comment]
![Screenshot_20210728-114650_Waistline.jpg](https://user-images.githubusercontent.com/1509654/127354224-33184683-543e-419e-b11a-b8e77d8d5186.jpg)

**Comment by davidhealey** [comment]
Yup that's a weird one

**Comment by davidhealey** [comment]
I think this is something to do with the viewport meta in index.html. Since I don't have a device (or emulator) with this issue I can't test it myself. I'll see if I can make a test app to narrow down this issue with various settings that can be tweaked and you can tell me if it works on your device. I won't have time to this for a little while though.

**Comment by davidhealey** [comment]
On second thoughts maybe I just need to add `height=device-height` to the meta. We'll try that first.

**Comment by davidhealey** [comment]
Please let me know if this is fixed in the latest version https://github.com/davidhealey/waistline/releases/tag/3.0.1

**Comment by longestmt** [comment]
> Please let me know if this is fixed in the latest version https://github.com/davidhealey/waistline/releases/tag/3.0.1

It worked!

**Comment by davidhealey** [comment]
Excellent, thanks for confirming.
