### ISSUE TITLE
Feature Request: add excercise in diary

### ISSUE THREAD

**Issue by azzamsa** [davidhealey/waistline#321]
Hi.

I am new to the waistline. I am curious why it does not have an exercise section in the diary. 
It looks like other app had this feature. They subtract the daily calories goal for what we eat and add it if we do exercise.

Thanks for the waistline.

**Comment by davidhealey** [comment]
2 Reasons:

* I have no interest in tracking calories used during exercise
* Most lookup tables of exercise <> calories are very generic, inaccurate, and not particularly useful. Everyone burns calories at a different rate and differently for each exercise. And each activity has many variables, just going for a 1 mile walk can produce hugely different calorie burns in one individual depending on the terrain, the temperature, etc.

You can actually already track exercise manually. Add a category to the diary called Exercise, and use the quick add (tab and hold the + button) and enter a negative calorie value. I could also make it possible to enter negative values into food items if you wanted to add "exercise" items to the food list.

**Comment by azzamsa** [comment]
Got it. I can add custom category in diary. However, as you said, currently I am not able to enter negative value.   

I agree to your point above. However, how do you know if you hit the daily calories goal without inputting the exercise?, I am curios about waistline user workflow. I track my diet to loose weight and I think tracking burned calories is also important.

**Comment by davidhealey** [comment]
> However, how do you know if you hit the daily calories goal without inputting the exercise?

I sit on my butt writing software all day, exercise calories are not having a big impact on my waistline :)

> currently I am not able to enter negative value

You can with quick-add but I'll add this to the food list too at the weekend.

> I track my diet to loose weight and I think tracking burned calories is also important.

Let's say you have a calorie limit of 2000kcal. If you did exercise that you believe burned 500kcal you might then think you could eat an additional 500kcal. But because of the inaccuracy of "burned" calories this could be an erroneous assumption and could lead to you putting on weight. For the average user who want to lose weight I think it's better to treat exercise burned calories as a bonus (that's how I treat it).

For someone who is into regular exercise and tracking their burned calories in more detail, in a gym environment for example, they probably have a more accurate view of how many calories their particular body burns under particular exercise conditions. For those people I can see tracking burned calories as less of a "risk" but since I'm not one of those people and I don't think the majority of people who want to lose weight are those people I have no plans to include is specifically in the app. But I think adding negative values to the food list should be a suitable work around.

**Comment by azzamsa** [comment]
> I sit on my butt writing software all day, exercise calories are not having a big impact on my waistline :)

:), got it.   

> You can with quick-add but I'll add this to the food list too at the weekend.

nice!

> I think it's better to treat exercise burned calories as a bonus (that's how I treat it).

nice idea, I will eat at my daily calories goals, regarding the exercise. 
this will make sure I don't have a surplus calories intake.

> Another idea I've been toying with is adding food categories, this could also include an exercise category, but I need to do more thinking about this.

Thanks a lot for waistline.

**Comment by ereinstein** [comment]
> Another idea I've been toying with is adding food categories, this could also include an exercise category, but I need to do more thinking about this.

I was just searching for a feature request regarding food categories. Since that seems to be somewhat related to this issue, I am not sure if I should still create a new feature request for food categories. 

Personally, I started using the app (which is fantastic btw) two days ago. I've added a few foods and two meals already but the overview quickly became a mess. Some form of categorising beyond just foods, meals and recipes would greatly enhance organisation. Maybe even add in some colour coding or the option to hide some foods which you solely added for including them in recipes. Though this isn't really much of an issue if you sort by frequency since those foods will land at the bottom of the list.

As for exercise tracking itself, [RunnerUp](https://github.com/jonasoreland/runnerup) has some great integrations with other apps and devices which could deliver the necessary input. I am not much of a coder myself but maybe some form of integration of RunnerUp into Waistline or some form of communication between those two apps could be used for tracking exercise beyond just guesstimating. This could be a great opportunity to strengthen the open-source exercise and food tracking ecosystem as well.

**Comment by davidhealey** [comment]
Make a separate issue for the categories so I can track it more easily.

As far as integration with other apps goes, it's not something I have any interest in adding as I don't use those apps and don't want to be responsible for implementing, testing, and maintaining something that I don't use. But if someone else implements it in a sensible way I'll merge it into the codebase.

**Comment by davidhealey** [comment]
Negative values done - https://github.com/davidhealey/waistline/commit/4be2c334091ad76b5ef278b6adedc545fb42a42d

**Comment by azzamsa** [comment]
Thanks a lot. Now I just need to wait a new release.

**Comment by davidhealey** [comment]
> Thanks a lot. Now I just need to wait a new release.

There have been a lot of releases since then.
