### ISSUE TITLE
Categorising foods, meals and recipes

### ISSUE THREAD

**Issue by ereinstein** [davidhealey/waistline#328]
Right now, the items in foods, meals and recipes are presented in a plain list without any further categorisation. This method of organising the items quickly becomes a mess. I'd like to propose categories which you can create on your own like e.g. dairy, convenience, fruits, etc. so that you can organise the items a bit better. 

Being able to colour code items for easier recognition or further categorising might be a nice addition as well. This could be overlapping with #325 depending on how far one wants to go with custom colours.

**Comment by davidhealey** [comment]
@EmilJunker Have you implemented this or are these just mockups? I like the idea, I think the UI spacing might be improved slightly and there should be a setting to toggle the option. Are the icons assigned automatically or is it manual?

**Comment by EmilJunker** [comment]
> Have you implemented this or are these just mockups?

I haven't implemented anything. These are real screenshots from the latest release. I'm simply using emoji in the food names.

Admittedly, a dedicated implementation with a category picker would make this a lot easier to use. But it's not strictly needed.

**Comment by NK308** [comment]
The emojis are a nice workaround, but I think the best option would be to assign labels to the entries and filter for those labels.

This could be much faster, since there could be design convenient popup dialogues when adding a new entry, or you could apply a filter to the list with two finger taps, when there is a specific button present. Also it could be made possible, to add multiple labels to an entry, so that it could be 'breakfast' and 'favorite' at the same time.

This should be faster than searching for emojis on a smartphone keyboard.

**Comment by EmilJunker** [comment]
@NK308 I agree with you. As I said, as soon as I have time, I will look into ways to implement this properly.
