### ISSUE TITLE
Cannot leave settings pages

### ISSUE THREAD

**Issue by michmxx** [davidhealey/waistline#382]
Hi David,

I just downloaded Version 3.1.10. On the settings page or on "About" the general back button cannot be used to leave the page. I know how to do it using the three lines menu but this behaviour is not intuitive (to me).

Regards
Michael

**Comment by davidhealey** [comment]
> 3.1.11 is the latest by the way

They're the same except for a few minor changes to some locale strings. The main reason to bump the version number was to trigger a rebuild on f-droid where we were having some issues.

> On the settings page or on "About" the general back button cannot be used to leave the page.

That's because those are top level pages, there is nothing to go back to. It's the same if you go to the diary or the food list for example. You can also swipe from the left side of the screen to bring up the menu.
