### ISSUE TITLE
Uninstalling app deletes backups

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#410]
We need to put the backups in a different folder, android still clears them from the media folder when uninstall the app.

**Comment by h-h-h-h** [comment]
It would be great if a de-facto standard could be established together with other apps to use one common folder for backups and app data not placed in the default system directories. The "root" folder (`/storage/emulated/0`) can get quite crowded. I have these folders from other apps (while there are already enough other ones, I'll never use):

- `gmmp` with app data from [GoneMAD Music Player](https://play.google.com/store/apps/details?id=gonemad.gmmp)
- `Librera` with app data from [Librera](https://play.google.com/store/apps/details?id=com.foobnix.pro.pdf.reader)
- `My Opening Hours` with backup from [My Opening Hours](https://play.google.com/store/apps/details?id=com.meneltharion.myopeninghours.app)
- `Smart AudioBook Player Backup` with backup from [Smart AudioBook Player](https://play.google.com/store/apps/details?id=ak.alizandro.smartaudiobookplayer)

The name would need to be well-thought-out, because it would be permanent.

**Comment by EmilJunker** [comment]
I tried to move the backups into the Documents folder (`/storage/emulated/0/Documents`). This seemed to work at first, and the backup files weren't deleted when I uninstalled the app! However, after I reinstalled it, the app could no longer read (or overwrite) the backup files from the previous installation. So I don't think this is a viable option.

On the plus side, I was able to implement a file picker using https://github.com/cyph/cordova-plugin-chooser that allows me to select and import a backup file from an arbitrary location (and apparently doesn't require any permissions).

**Comment by davidhealey** [comment]
> On the plus side, I was able to implement a file picker using https://github.com/cyph/cordova-plugin-chooser that allows me to select and import a backup file from an arbitrary location (and apparently doesn't require any permissions).

Can this also be used to select a location to store backup files?

**Comment by EmilJunker** [comment]
> Can this also be used to select a location to store backup files?

Unfortunately not. It only lets me select existing files (and not directories).

**Comment by davidhealey** [comment]
Ah that's a shame, but still useful to be able to select the file to load.
