### ISSUE TITLE
fat app

### ISSUE THREAD

**Issue by gilcot** [davidhealey/waistline#42]
Hello,

I can see, via F-Droid, that version 1.0.0 was 3.5 MiB then version 1.0.2 was 2.2 MiB :+1: But version 2.0.0 jumps to 6.6 MiB (triple times the previous size ...and can no longer fit my device) with compatibility break :-1: Why on earth ?!?

**Comment by davidhealey** [comment]
Version 2 uses a different GUI library and adds lots of new features - it's essentially a complete rewrite. There may be some optimization I can do to bring the size down a bit, I'll check when I do the next update.

**Comment by gilcot** [comment]
Hi @davidhealey 

Thanks for the quick reply.  
I read in the changelog that v2 is a "simple GUI update" so it shouldn't increase so much, is it?   
I also read that you made a "Complete UI rewrite using OnsenUI instead of jQuery mobile". Can the library be better when being so much bigger and less known (imho, I'm not a developer)

**Comment by davidhealey** [comment]
I think this is the line you are quoting from the change log

> What started out as a simple GUI update turned into pretty much a complete rewrite. 

I've just done a comparison and jQuery Mobile is 18.7mb while Onsenui is only 10.8mb so onsen is actually smaller. Popularity has nothing to do with how good something is, especially in the world of software development.

Since version 1 of Waistline I've added extra images for icons and the splashcreen, I've also added  functionality like the ability to upload images to Open Food Facts, which required the addition of extra Cordova plugins. i guess the addition of all these little extra files adds up to a bigger app. There are some optimizations available when compiling Onsen that I didn't set so I will look into that for the next update.

**Comment by davidhealey** [comment]
I've shrunk the latest version as much as I can, if I find more optimizations that will reduce the size more I will apply them

**Comment by gilcot** [comment]
Hi,

Sorry, I've been busy and didn't read your replies. You're right:
> Popularity has nothing to do with how good something is, especially in the world of software development.

I just mean one is well established and _looks_ smaller --when I compare the results-- so I don't really understand the change reason. But as the newest is smaller (10.8 MiB vs 18.7 MiB) there must be other things wrong...
> I've shrunk the latest version as much as I can

My little device, not full of rooms, thanks you for taking that in consideration. I'm waiting to test the next release and test all the new additions you made (yes, I wasn't able to update since version 2)
