### ISSUE TITLE
Automatic dark theme for Android 10+ 

### ISSUE THREAD

**Issue by ghost** [davidhealey/waistline#463]
Most modern applications support an option to follow the system wide dark theme. It would be greatly appreciated if you could make it.

**Comment by davidhealey** [comment]
I second the sentiment of your username :)

**Comment by EmilJunker** [comment]
Framework7 has an `autoDarkMode` parameter ([docs](https://framework7.io/docs/app#param-autoDarkMode)), so this should be possible. But implementing this feature could require some work because it looks like the parameter value cannot be changed while Waistline is running, so changing the theme would sometimes require an app restart.
