### ISSUE TITLE
Backup takes forever. Show progress?

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#470]
I tried exporting from the settings. But after 11 minutes, it's still not finished and only showing the spinner. I had to abort the operation. I'm using Waistline for nearly 2 years now (because of the amount of data to be exported).

- Is there something buggy?
- A progress bar or at least a percentage would help.
- I have automatic backup enabled. But `/storage/emulated/0/Android/data/com.waist.line/files/waistline_export.json` still has the date 2022-01-13 from my Waistline v2 export. Is that to be expected, frequency-wise?
- When trying to export and while the spinner shows, I'm able to use the OS's back button to go up in the settings and the spinner overlay persists. Any tapping on the screen doesn't do anything, though. I have to kill the app.

**Comment by EmilJunker** [comment]
Which version are you using? The latest version is `3.2.2`. And where did you install it from, Play Store or F-droid?

> Is there something buggy?

Not that I know of, but the backup clearly shouldn't take more than a few seconds, so something must have went wrong.

> A progress bar or at least a percentage would help.

That's not so easy to implement. And also shouldn't be necessary since the backup normally only takes a few seconds.

> I have automatic backup enabled. But /storage/emulated/0/Android/data/com.waist.line/files/waistline_export.json still has the date 2022-01-13 from my Waistline v2 export. Is that to be expected, frequency-wise?

I believe the automatic backup takes place every time you launch the app. But if you can't create a manual backup, it makes sense that the automatic backup isn't working either (internally, it's all the same procedure).

But the file path you mentioned is actually outdated. Recently (I don't remember when exactly), the backup location was changed to `/storage/emulated/0/Android/media/com.waist.line/waistline_export.json` because the old location wasn't accessible on non-rooted Android 11 devices.

The new backup location in the media directory is more easily accessible, but it has the disadvantage that the app needs permission to write to it. Normally, the app should ask you for permission the first time you try to create a backup. But you an also go to your device settings and grant the permission there.

> When trying to export and while the spinner shows, I'm able to use the OS's back button to go up in the settings and the spinner overlay persists. Any tapping on the screen doesn't do anything, though. I have to kill the app.

Maybe the app should detect whether the access permission has been granted and abort with an error message if it hasn't.

**Comment by h-h-h-h** [comment]
> Which version are you using? The latest version is 3.2.2. And where did you install it from, Play Store or F-droid?

I'm using the latest version `3.2.2` from F-Droid.

> the backup location was changed to `/storage/emulated/0/Android/media/com.waist.line/waistline_export.json` because the old location wasn't accessible on non-rooted Android 11 devices.

That folder is empty. And I *could* access the old folder under Android 11 without root. (I'm using TotalCommander on Android. And I'm on Android 12 now.)

> The new backup location in the media directory is more easily accessible, but it has the disadvantage that the app needs permission to write to it. Normally, the app should ask you for permission the first time you try to create a backup. But you can also go to your device settings and grant the permission there.

I have the storage permission set to denied, as the Android settings show. That will be it.

> Maybe the app should detect whether the access permission has been granted and abort with an error message if it hasn't.

Can't the app settle for something less than getting access to the *whole* storage? Isn't there something new like scoped storage?

If the old directory was accessible for the app without unnecesserily wide access, I'd prefer this one. How about an informational label on the backup page that tells you that the backup will be stored in `.../media/...`, but that you can deny storage access and, in this case, `.../data/...` is used. Could also be done with a switch.

**Comment by EmilJunker** [comment]
> I could access the old folder under Android 11 without root. (I'm using TotalCommander on Android. And I'm on Android 12 now.) 

On my phone (running Android 11), I can't access the content of the `.../Android/data/` directory with the default file browser. However, using a different file app, I can access it for some reason.

Anyway, several other users were complaining about this too (see issue #252) and that's why it was changed. There is even an [official blog post](https://developer.android.com/about/versions/11/privacy/storage)  about the storage updates in Android 11.

> I have the storage permission set to denied, as the Android settings show. That will be it.

I thought so. Can you confirm that granting the permission resolves the issue?

> Can't the app settle for something less than getting access to the whole storage? Isn't there something new like scoped storage?

Not that I know of. Also, even if there is some kind of new permission model, keep in mind that it would need to be supported by Cordova and should work on older versions of Android too.

> If the old directory was accessible for the app without unnecesserily wide access, I'd prefer this one. How about an informational label on the backup page that tells you that the backup will be stored in .../media/..., but that you can deny storage access and, in this case, .../data/... is used. Could also be done with a switch.

That seems like a needlessly complicated solution that's looking for a problem ;)

But seriously, I think our priority should be to fix #410 instead of worrying about app permissions.

**Comment by h-h-h-h** [comment]
> Can you confirm that granting the permission resolves the issue?

Yes, it works in the blink of an eye after having granted the permission.
