### ISSUE TITLE
Diary breaks completely

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#479]
To reproduce:

- Press `+` in diary.
- Press circled `+` in food list, create food and save.
- Delete the same food. While doing this, the top-left button's icon already incorrectly changed from `←` (arrow) to `☰` (hamburger).
- Go to diary via hamburger icon. The diary is now completely broken: no date, no sections, no bottom bar content; arrow buttons do nothing visually. When I add an item via food list, the bottom bar and the section with my single category shows including previously added items of the day, but not the date. When I press any arrow button including the left one, the date shows and is always *advanced*. (The date for which the item is added depends on how often you previously pressed the arrow buttons in the contentless diary, where any arrow button press also advanced the date in the background.) I have to restart the app to get things back to normal.

**Comment by EmilJunker** [comment]
Damn, I tought I had fixed that. This problem was a lot worse in versions prior to v3.2.3. You could break it simply by pressing `+` in the diary, then opening the hamburger menu by swiping, and navigating back to the diary. Commit https://github.com/davidhealey/waistline/commit/caa6a50a2f44e4194ca39fee77caa954406a6954 was supposed to mitigate this problem, but apparently it's not completely fixed.
