### ISSUE TITLE
Lots of food items showing up with 0kcal

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#482]
This is happening in the search, if it was the odd item I wouldn't think anything of it, but I smell a bug.

Searching for Yorkshire Pudding brings up several results with 0kcal

**Comment by EmilJunker** [comment]
Are you talking about these?

- https://world.openfoodfacts.org/product/0813715010062/yorkshire-puddings-and-pancakes
- https://world.openfoodfacts.org/product/5053526876012/tesco-giant-yorkshire-pudding
- https://world.openfoodfacts.org/product/5051140030674/12-yorkshire-puddings-tesco

They seem to have no calorie values set in OFF, so Waistline simply displays them as `0 kcal`. I think this is fine. It is important that Waistline can also find OFF entries like this because there are some items that really have no calories, e.g. dietary supplements like this one:

- https://world.openfoodfacts.org/product/4316268448895/vitamin-c-zink-selen-vitamin-d3-brausetablette-prolife

Anyway, there is also a Yorkshire Pudding item that has a calories value set in OFF but in Waistline it still shows up with `0 kcal` for some reason:

- https://world.openfoodfacts.org/product/5000227985338/aunt-bessie-s-12-bake-at-home-yorkshire-puddings

I will see if I can get this fixed...

**Comment by davidhealey** [comment]
Yeah, that's a good idea!
