### ISSUE TITLE
Backup data to the cloud feature

### ISSUE THREAD

**Issue by tavva** [davidhealey/waistline#506]
Keeping diary data on the device is highlighted in the app description. Would you consider an optional option to allow backups to the cloud to allow for easy data sharing?

Context: I'm building a personal data dashboard and Waistline looks like the best diary app, albeit Android-only. I'd like to automate data transfer as much as possible, so having data exported to e.g. Google Drive regularly would afford easy import into other apps.

I wouldn't work on this immediately, but wanted to check this would be an option for me to submit a PR for further down the line. Thanks!

**Comment by davidhealey** [comment]
I'm not opposed to the idea but I don't know how to implement it without integrating into the APIs of specific web services, like Google Drive, which I am opposed to. If there is a generic system for uploading the data to an arbitrary location then that's something I'd think is acceptable.

**Comment by tavva** [comment]
Thanks! Curious as the reason for your opposition to implementing against cloud provider APIs?

**Comment by davidhealey** [comment]
> Thanks! Curious as to the reason for your opposition to implementing against cloud provider APIs?

- Every service will need a separate implementation
- On going maintenance, especially when the API changes
- If there is an issue with the service I will get support requests from users - this already happens when Google breaks something in Chrome or Android
- If one of the services stops being supported then more support requests and more maintenance will be required.
- The whole point of Waistline is that your data is stored locally :)
- I won't use it

**Comment by tavva** [comment]
Thanks David!
