### ISSUE TITLE
allow user to specify amount / quantity of an item

### ISSUE THREAD

**Issue by grrrrr** [davidhealey/waistline#51]
When importing items from OpenFoodFacts there does not appear to be a way to specify how many of a food were eaten.  Can it be possible to get a feature to specify the quantity of a food item

For example if I scan a cookie in from OFF it will give me the per cookie stats. If I have eaten two, I can only see the option of either adding two separate entries for a cookie  making the diary longer than it needs to be or editing the cookie statistics and doubling everything.

**Comment by davidhealey** [comment]
With the latest version you can edit the portion size in the edit food window. I need to update the user manual to explain this.

**Comment by grrrrr** [comment]
does it make sense to do it there?    If I've imported from OFF  I get

    name: Cookie
    brand: whatever
    portion:  37
    unit: g

Which is the info for 1 cookie.   If I have `n` cookies,  instead of setting a quantity field to `n` and letting `waistline` do the working out for me, I have to figure out what `n`*37 is.

**Comment by davidhealey** [comment]
Ah so you want a number of servings option like on the diary page? I think this is a good request so I'll add it to the list.

**Comment by grrrrr** [comment]
Yes,  sorry for confusion

**Comment by davidhealey** [comment]
I was just looking at this issue and it occurred to me that what you want is already there (although there is a bug at the moment that I need to fix). Instead of entering 37g as the portion you should enter 1 cookie. Then after you've entered the nutritional info for 1 cookie you can change the portion to any other number and all of the data will update automatically. Like I say though there seems to be a bug currently where changing the portion clears the data so I'll fix this today.

**Comment by davidhealey** [comment]
Ok I've fixed and improved this now. It will be in the next update.
