### ISSUE TITLE
Slight changes in average goal lead to jumps

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#519]
I have the following settings:

- Same goal every day
- Automatic goal adjustment to meet average goal
- Calculate average goal based on last 10 days

I just reduced my calorie goal by 50 kcal. But the goal in the diary was reduced by several hundred kcal. I wanted the slightly reduced daily goal to apply from today on, not since 10 days ago or whatever the app did, making me pay an added up price. For bigger changes, the goal display must be rendered unusable.

It would be best if the app knew and considered the dates of goal changes and what applied before, at least for the duration of the average calculation.

**Comment by EmilJunker** [comment]
As you already noticed, Waistline doesn't keep track of goal changes. It assumes that your current goals also apply to all days in the past (and future). From the app's perspective, it now looks like you overate by 50 kcal on each of the past 10 days, so your goal for today is reduced accordingly.

To fix this problem, we would need to completely rework the goals system, and I don't see that happening (at least not anytime soon). 

The immediate solution to this problem is for you to disable the auto adjust feature for now, and enable it again in 10 days. Or you could temporarily base the average goal calculation on the current week, assuming today (Monday) is your first day of the week.

**Comment by h-h-h-h** [comment]
I'm just trying it with a higher count of even smaller changes.

Wasn't it the case with Waistline v2 that it remembered the goal for each day? So, that changed fundamentally can't be reinstated? Because the averaging feature doesn't need to adjust past goals anyway. And I already found it strange in the past when I changed a goal and the numbers in the bottom bar of past days got red.

**Comment by EmilJunker** [comment]
> Wasn't it the case with Waistline v2 that it remembered the goal for each day? So, that changed fundamentally can't be reinstated?

I'm not too familiar with Waistline pre v3, but it looks like you're right. I just checked one of my old backup files from Waistline v2, and it stored the goals separately for each day in the log table (which has since been removed in v3).

**Comment by davidhealey** [comment]
I think it might be worth storing goals by date so that past days are not affected by changes to the goal. This might have some knock-on effect on the stats page though.
