### ISSUE TITLE
When adding recipes as a diary entry, add as one item not the individual ingredients

### ISSUE THREAD

**Issue by grrrrr** [davidhealey/waistline#53]
At the current time, if you create a recipe made up of multiple items, when you add this recipe to the diary it gets added as the individual components of the recipe.

This can make the diary hard to read when you add a recipe with lots of items.

I would like suggest instead that when you add a recipe  in the diary  it gets listed as one item with the recipe name and the totals of the combined ingredients

**Comment by davidhealey** [comment]
Lets say I make a sandwich recipe that has cheese, eggs, ham, and ketchup, and I add it to my diary. Another day I have the same sandwich but I don't have any egg, I would have to create a new recipe for this minor change if the recipe was added as a single item like you suggest. But with the current system all I do is add my original recipe and remove the egg from the diary.

There is a more technical reason too. The diary only recognizes food objects and only the recipe system recognizes recipe objects (which are kind of like mini diaries). It would require substantial alteration to add a recipe object to the diary and I currently don't have a need for that.

**Comment by grrrrr** [comment]
Makes sense,  I thought it might work like the food list.  Where if you add a food from the list to your diary you can safely delete it from the list and it stays in the diary.   I wrongly assume I think that the totals and name could be added and the original entry updated as you outlined above if needed

**Comment by Mitlik** [comment]
I too was surprised by how this feature worked. I really expected to make the recipe and then scale it as a whole in the diary. Would it be possible to add a servings field that allows the whole recipe to be entered but doesn't require refiguring on each use? In your example sandwhich the serving would be 1, but for a giant pot of soup those 3 potatoes might be issued out over 8 servings.

**Comment by davidhealey** [comment]
I'll have to think of a way to add it to the interface. If it was just a single recipe being added to the diary then a popup box could be used to enter the number of servings but this wouldn't work with the multi-add system.

Regarding my own usage. I always enter my foods into the food list as a single serving which results in each recipe being a single serving size. But I can see other uses which I haven't yet explored, for example using the recipe system for actual recipes (like a cake) rather than a collection of foods that make a single meal. Definitely some interesting possibilities.

**Comment by gwenhael-le-moine** [comment]
You might want to split between:
- recipes as a bunch of ingredients and a number of servings added as a whole to the journal,
- "saved meals" as the way recipes work now.

**Comment by davidhealey** [comment]
I was thinking perhaps just double tapping a recipe to add it with a serving size and the multi-add would still work as it does now.

**Comment by Mitlik** [comment]
For what it's worth, I tried using the recipe function more in line with what @davidhealy described. As I am considering this issue, I'm not sure why I assumed it would work a certain way, either ingrained from similar apps or because I do a lot of cooking or what.

I wanted to build the nutritional information for a recipe from simple ingredients I would buy from the store (e.g. I make alfredo using noodles, butter, flour, cream, and two cheeses). But when using it, there was no easy way to scale to a single serving and the diary becomes cluttered. One could use that clutter to form a shopping list, however I assume that is outside the project scope.  It sounds like the recipe list was intended more for complex ingredients. If I create that base alfredo as item, then I can create variations of it easily from those more complex ingredients. So steak Gorgonzola alfredo and chicken chipotle alfredo become 3-4 ingredient recipes that work great with the multi-add. Using the more complex ingredients also makes it easier to control the serving size at the recipe level.

Hopefully that didn't rehash everything in the thread. I just wanted to share, I tried the developer's way and liked it. Maybe automatically adding user created recipes as an item in the local food db (or allow recipes to use other recipes as ingredients) would be a way to satisfy both use cases?

> 
> 
> I was thinking perhaps just double tapping a recipe to add it with a serving size and the multi-add would still work as it does now.

 It wasn't clear to me if the double tap would scale all ingredients and then add them as individual ingredients (via multi-add) or if double-tap and multi-add would be two mutually exclusive functions.

**Comment by davidhealey** [comment]
> It wasn't clear to me if the double tap would scale all ingredients and then add them as individual ingredients (via multi-add). 
This was my intention

> Maybe automatically adding user created recipes as an item in the local food db (or allow recipes to use other recipes as ingredients) would be a way to satisfy both use cases?
This is an interesting suggestion. The only problem I can see is that if the recipe is deleted from the recipe section it will remain as a food in the food list and vice versa.

**Comment by davidhealey** [comment]
> You might want to split between:
> 
>     * recipes as a bunch of ingredients and a number of servings added as a whole to the journal,
> 
>     * "saved meals" as the way recipes work now.

Yes I think I'm going to adopt this approach in a future update. Not 100% sure how it will work in terms of passing things between the recipe, meal, and food list, but I'll work something out.

**Comment by davidhealey** [comment]
This has been implemented now (will be available in the next update)
