### ISSUE TITLE
Can't add food to meals from diary menu

### ISSUE THREAD

**Issue by DeadManIV** [davidhealey/waistline#538]
I can't add food to meals from the diary menu. Not sure if this was always the case, but seems like a flaw. You can add food to meals if you go directly to the foods menu (not through the diary menu)
Have included a video below.

Edit: am using version 3.3.3

https://user-images.githubusercontent.com/9134591/161380270-e4f0babf-e862-4186-937d-83b7938f98cf.mp4

**Comment by EmilJunker** [comment]
This is not a bug. I changed this on purpose in #511 in order to fix #503 and #479.

If we allow adding foods to a meal when coming from the diary, this essentially causes the foods list to be loaded twice (`Diary > Foods list > Meal editor > Foods list`) which seems to cause issues in the internal routing (see #503 and #479). That's why I changed it. I've already done my best make this as user friendly as possible by at least allowing you to peek into the meal, but not to edit its ingredients.

**Comment by EmilJunker** [comment]
Oh I just realized it would make sense to also hide the `+` button in the meal list when coming from the diary because you can't add food to the meal anyway. This would probably clear up some of the confusion.

**Comment by davidhealey** [comment]
Good idea

**Comment by DeadManIV** [comment]
Would it be a good idea to also prevent you from deleting items from meals when you access them from the diary menu? And maybe have a pop-up/notification that tells the user that they can't add/delete meal items from the diary menu?

**Comment by EmilJunker** [comment]
Deleting items from a meal is not problematic, so we don't need to prevent it.

**Comment by DeadManIV** [comment]
My experience when seeing this issue was that I thought it was a bug. So I tried deleting an item just to see if it works, and then I couldn't re-add the item from the same menu and I thought I had messed up that meal permanently - until a bug fix was issued. Or until I realised that I could still do it from the meal menu. I think it feels a bit inconsistent to be able to delete items but not add items from the diary menu. It's like having an edit vs a view mode, except you have half of the features of the edit mode. Hope this makes sense, if you decide not to change it, no worries, just giving my two cents.
