### ISSUE TITLE
Question about recipes and tracking

### ISSUE THREAD

**Issue by xddq** [davidhealey/waistline#552]
I am mostly using recipes to track my daily calories since they can be scaled (say, 1/2 of the recipe because I did share the meal with soneome).

So far so good.

But whenever I adapt a recipe all diary entries will be adapting. Resulting in completely wrong statistics. Which makes them useless for me.

Am I doing sonething wrong?
**How can you scale meals and have correct statistics?**

Thanks in advance!

version: 3.4.0

**Comment by davidhealey** [comment]
Any change you make to a food or recipe will affect all past and future entries that use those items.

In the old version of Waistline it didn't work like this, the list of items added to the diary was independent of the food/recipe lists. This meant that any changes made to a food/recipe would not affect entries already in the diary.

I received multiple feature requests to change this, so that adjustments to a food/recipe alter past diary entries and this is the behaviour with have in the current version.

I have found that I don't like it changing past entries, except on rare occasions when I'm correcting a mistake in the data. Generally I prefer each diary entry to be a snapshot of that day and any changes I make to a food (for example if the manufacturer adjusts the recipe) I want to only affect new entries.

So I think it would be better to find some system that accommodates both scenarios. Perhaps when saving a food item it can show a prompt and ask if you want to update all old entries, although I'm more inclined to put this as a global setting so I don't get prompted every time. 

I think this would also solve your issue.

The only downside is this will require a major restructuring of the database and some decent testing to make sure it doesn't mess up existing data. So it probably won't be implemented for a while.

**Comment by EmilJunker** [comment]
I much prefer the current system where the diary only contains a reference to the food item or recipe which is stored in a separate table. This is way cleaner, and more future proof too. Also, think about how much storage we save by doing it this way.

That's why I'd suggest a different approach: Currently, when you delete a food item or a recipe, it isn't actually deleted, but marked as archived and hidden from the food list. For items with a barcode, if you later rescan the barcode or search for it, the archived item is unarchived again, so any changes you make to the nutrition values are applied to all existing diary entries that reference this food. To fix this, we should add an option to not unarchive the existing item with the barcode, but to create a new item that can have different nutrition values. Obviously, this would require us to drop the uniqueness constraint in the barcode index of the foodList table. I don't know if this will have any implications, but it should be manageable.

As for recipes (which the original post was about), the solution would be to delete the old recipe (though this is optional, you may also keed it), and to create a new one whenever you adapt the recipe. Of course, the ability to copy meals and recipes (as suggested in some other issues) would help with this.

**Comment by xddq** [comment]
Interesting that many people requested this feature..

What is the actual advantage of this?

The disadvantage is not having decent/correct statistics if you ever change your recipes.

I don't think storage is a big concern for most users. It is stored text after all.


Anyway, thanks for your good work, guys. Besides that, the app is really useful
