### ISSUE TITLE
Possible bug regarding dates

### ISSUE THREAD

**Issue by Rhadlaren** [davidhealey/waistline#576]
I ran into an issue regarding an inconsistency between the dates and data values in the Diary page, and the corresponding dates and data values in the Statistics page.  Basically, at least for me, the Statistics tables and plots seem to have their dates shifted by one day (the Statistics page seems to be associated with the data of the previous day). 

Let me try to clarify by an example:  Today, I opened the app to the Diary page (my default), and it displayed the correct date (April 28, 2022 in this case).  I went ahead and clicked the scale icon and entered my weight that I measured this morning.  It saved, and all of my data from previous days were associated with the proper dates.  Then, I switched to the Statistics page, scrolled down to see the data list, and the weight I just entered was associated with yesterday's date (in this case, April 27, 2022).  So basically, there is an incorrect shift in the dates relative to the data values.

I'm new to the software, so it's possible I have set something up wrong, but I don't see an option to fix this. I looked through the Github Issues archive, and couldn't find this particular issue, so I thought I would post it in case others experienced the same problem!  I wonder if this may be some simple array indexing error (or maybe a timezone inconsistency if the data is stored remotely somewhere)?

Here is my version/OS info:  Waistline v3.4.0; Android v12, Galaxy S20+

Thanks very much for creating/maintaining this software!  I very much like the fact that it is Open Source and data privacy-oriented.

**Comment by EmilJunker** [comment]
You are right, this is a bug. And it's interesting that nobody had noticed it until now. That might be because it only affects people who live west of the IERS Reference Meridian, which conveniently excludes pretty much all European countries :)

Let me explain: Internally, the Diary stores all dates in UTC time, i.e. the weight value you entered today is associated with the timestamp `2022-04-28T00:00:00.000Z`. On the statistics page, these timestamps are then printed out with JavaScript's `toLocaleDateString()` function which by default uses the local time zone. Obviously, when it is midnight on the 28th of April in UTC, then it is still the 27th of April anywhere west of UTC.
