### ISSUE TITLE
Remove edit image option

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#579]
The edit image option doesn't work at all with my phone since we updated to the latest cordova camera plugin. This seems to be a known issue with no proper solution.

I suggest we remove the edit image setting and disable that option in the takePicture function. We should then use cordova-plugin-crop to provide the cropping capability. https://github.com/jeduan/cordova-plugin-crop

I did a little test earlier today and this plugin seems to work nicely with file uri but not base64. So I suggest we go back to file uri and convert the cropped image to base64.

I don't have time to tackle this at the moment unfortunately but will try to get round to it in the next few weeks. @EmilJunker If you have time and want to give it a go please feel free.

**Comment by EmilJunker** [comment]
The reason I switched from the file URI to base64 is because when you select an existing image from the gallery (which is now possible in the latest release), it returns is the path of that file as file URI - and the problem is that Waistline may not have permission to read from that location. Switching to base64 avoids this problem.

**Comment by davidhealey** [comment]
Yeah I think we just need file uri for when using the camera so that we can make use of the crop plugin - although it would be nice to crop gallery images too. Then once the image is cropped use the filereader to convert to base64 and follow the existing flow you've implemented
