### ISSUE TITLE
Nonconsistent carbohydrate calculation

### ISSUE THREAD

**Issue by brqec77** [davidhealey/waistline#621]
Carbs are calculated different in Europe and the US: https://esha.com/blog/how-carbs-are-calculated-in-different-countries/
Hence, foods imported from USDA have carbs containing the amount of fiber and foods from Open Food Facts of European countries exclude the fiber from the carbohydrates.
As I import foods from both sources, it is not possible to distinct between the net carbs and total carbs intake.
For very lowcarb diets, it is important to know the net carb intake, which can differ from the total carb intake very much if you eat a lot of fiber.

It would be very beneficial to unify the amount of carbs per food.
Either substract the fiber of all foods from USDA and US products from Open Food Facts,
or add the fiber to all European products from  Open Food Facts.

Instead of automatically correcting the amount of carbs, a half-automated solution, using a checkmark during the import would also be convenient.

At the moment I either have to calculate  and correct the carbs by hand, or I have to export my database and recalculate the carbs using some kind of script.

**Comment by EmilJunker** [comment]
Wow, I didn't know there were such differences in nutrition labelling between countries. Thank you for raising this issue.

> It would be very beneficial to unify the amount of carbs per food.

Yes, I agree. Unfortunately, this is easier said than done :)

> Either substract the fiber of all foods from USDA and US products from Open Food Facts,
> or add the fiber to all European products from Open Food Facts.

For products from USDA, this should be very easy. As you suggested, we can simply subtract the fiber value from the carbs value during the import. However, for products from OFF, there is no way to know what kind of labelling the nutrition values are based on (US style or EU style). The information which countries the product is sold in doesn't really help here because it's often wrong or incomplete (and there are also products that are sold on both continents with the same barcode).

In my opinion, this issue sounds like something the people from OFF should take care of on their end. This is ouside the scope of Waistline.

Anyway, I think we should at least fix the import from the USDA database. I don't think this needs to be optional, we can simply always subtract the fiber value from the carbs value when importing from USDA. We could also add some code that automatically corrects the values for all previously imported foods from USDA. Of course, this would assume that the user hasn't already corrected the values manually.

**Comment by davidhealey** [comment]
@EmilJunker I agree, OFFs data is there problem. I don't think it's necessary to correct USDA values users have already entered, our user base is so small and this is a niche problem that it's not worth the effort and potential problems.

**Comment by EmilJunker** [comment]
Alright, I'll make a pull request that fixes the USDA import for newly downloaded items.

If anyone wants to programmatically correct the carbs values of all existing items, here is some code you can use. You can run this code directly on your phone from the `chrome://inspect` console. This only works if the APK you used to install Waistline is debuggable, though.

```js
await dbHandler.processItems("foodList", undefined, undefined, (cursor) => {
    let item = cursor.value;
    if (item.barcode !== undefined && item.barcode.startsWith("fdcId_")) {
        if (item.nutrition !== undefined && item.nutrition.carbohydrates && item.nutrition.fiber) {
            item.nutrition.carbohydrates = item.nutrition.carbohydrates - item.nutrition.fiber;
            cursor.update(item);
        }
    }
});
```

**Comment by nitrocode** [comment]
Couldn't there be a new field called net carbs for each item?
