### ISSUE TITLE
wrong pictures detected

### ISSUE THREAD

**Issue by benbenben2** [davidhealey/waistline#636]
In Croatia some uploaded pictures seems to have been taken from internet: 
https://hr.openfoodfacts.org/editor/waistline-app

See the following message in OFF Slack chanel for more details: 
https://openfoodfacts.slack.com/archives/CDC9K6RFT/p1663874548344869

**Comment by davidhealey** [comment]
Are you saying people are uploading pictures taken from the internet to OFF?

**Comment by benbenben2** [comment]
it looks like, yes

**Comment by davidhealey** [comment]
Not really a Waistline issue, I can't control what people upload.

**Comment by benbenben2** [comment]
ok, thanks
I will close this issue, then.

**Comment by CharlesNepote** [comment]
> Not really a Waistline issue, I can't control what people upload.

Yes, but could you at least ask them not to upload photos they have directly took themselves from the product?

**Comment by davidhealey** [comment]
We can always ask, but it doesn't mean they will. Do you have a suggestion for how to present this to a user without it being annoying? I'd hate a popup appearing every time I try to select a photo and showing it only the first time is probably not very useful because user's are apt to forget things.
