### ISSUE TITLE
Recipe editor should say # of servings  

### ISSUE THREAD

**Issue by amgarr** [davidhealey/waistline#642]
The recipe creator has a field for serving size but it should have a field for number of servings instead. Or alternatively should have both Serving Size & # of Servings. As it is currently I have been putting # of Servings in Serving Size field then when adding the food to diary adjust Serving Size field back down to 1.

**Comment by EmilJunker** [comment]
I think the serving size field is fine. In combination with the serving unit field, it provides the most flexibility.
If you set the serving unit to "servings", then the serving size field effectively functions as the number of servings. But in recipes for pies or cookies, for example, it makes more sense to use different serving units (e.g. 1 pie, 8 slices, 40 cookies, etc.). And then the serving size field can be set accordingly.

**Comment by amgarr** [comment]
I don't really understand. Generally serving size means how much is in a serving and the serving unit is the units. It doesn't seem intuitive to me but it is functional.  It would seem more straightforward and understandable if Serving Size was renamed "Servings" or "Total Serving". 

When you are adding it to the diary you are prompted for serving size and servings. It seems duplicative right now. In the case below if you ate 3 cookies you would adjust Serving Size to 1 and # of servings to 1.5. or you do the same in reverse. If there was a Number of Servings field in the Recipe creator then serving size could be used to actually describe the serving size. 

For example, recipe X would be able to have 
Number of Servings - 10
Serving Size - 25
Serving Units - grams

Currently you have to have
Serving Size - 10
Serving Units - 25 grams

![604f6d4b-85fb-4f4c-b05e-e21bcf5a533b](https://user-images.githubusercontent.com/96392700/194433723-8ce39e94-5b50-4727-b750-6da5c92f8712.png)
![2997a38e-81df-44b9-9e32-4c8ec5052daf](https://user-images.githubusercontent.com/96392700/194433753-f611789a-ca63-42b8-9836-c03c00e8f09a.png)

**Comment by davidhealey** [comment]
I see there is some confusion with how this works too. The implementation could do with some improvement or clarification.

**Comment by EmilJunker** [comment]
Maybe we could just hide the Number of Servings field for recipes in the quantity dialog and in the diary. For recipes it should be sufficient to specify the quantity via the Serving Size field.

**Comment by davidhealey** [comment]
I don't know if that would work. I like the idea that you can specify an amount in the recipe, let's say the recipe makes 10 cookies total, you could set the serving size to 10 and the unit to cookies, then when you add it to the diary it should take the total and divide it by 10 to create 1 cookie. I think another field will be needed to specify the divider, or perhaps there is an alternative method.

**Comment by EmilJunker** [comment]
@davidhealey For the use case you are describing with the serving unit set to cookies and serving size set to 10 (i.e. the recipe makes 10 cookies), the "serving size" field in the quantity dialog is sufficient. You simply need to enter the number of cookies you ate into the field, and the app does the math for you.

**Comment by EmilJunker** [comment]
That's why I'm proposing to hide the extra "number of servings" field to clear up some of the confusion. It is not really needed for recipes.

**Comment by davidhealey** [comment]
> the quantity dialog is sufficient

@EmilJunker What quantity dialog?

**Comment by davidhealey** [comment]
@EmilJunker I don't use that so the solution won't work for me ;)

**Comment by EmilJunker** [comment]
My idea was to hide the "number of servings" field in both the quantity popup and the diary food editor. This way, the solution works for everyone.

**Comment by davidhealey** [comment]
I get it, ok we can try that.

**Comment by pablob127** [comment]
I posted this in #645, but I'll post it here too for completeness.

This actually broke down one of the ways I was using to enter recipes!

For instance, I have a soup recipe where I have measured that the total quantity is 1350 ml, so I put 1350 ml as the serving size in the recipe. Then, when we share the soup equally between 4 people, I would just enter 1350 ml in the serving, and then 0.25 servings in the number of servings  so that the app would do the math.
With the hidden number of servings field, I need to do the math manually to enter the right amount in the serving size.

I would appreciate it if this change could be made optional (or another way to fix the original issue was found).

**Comment by EmilJunker** [comment]
I still think that this change was a good idea. I'm sorry if this broke one of your existing recipes, but we're trying to make this easier to use going forward, so that's a trade-off I'm willing to accept.

You can just archive the recipe and create a copy of it with a different serving size and unit. This will leave your existing diary entries unaffected and fix this issue going forward. 

To clear up the confusion, here are some examples of what to enter into the serving size field in the diary when logging a recipe:

- If the recipe unit is `cookies` and the recipe serving size is `20` (i.e. the recipe makes 20 cookies), enter the number of cookies you ate.
- If the recipe unit is `servings` and the recipe serving size is `4` (i.e. the recipe makes 4 servings), enter the number of servings you ate.
- If the recipe unit is `cake` and the recipe serving size is `1` (i.e. the recipe makes 1 cake), enter the share of the cake you ate, e.g. `0.333`.

**Comment by pablob127** [comment]
I guess I am more quantitative than the average person, I liked the previous system better. I'll see how many of my recipes are affected by this, maybe there are less than I think.
In any case, thank you very for all you do for Waistline!

**Comment by pablob127** [comment]
I guess I got used to it. Only what I say now counts, of course! :stuck_out_tongue_winking_eye:

I'll get used to this one, and then I'll complain again when it changes. :smile:

**Comment by Tinsus** [comment]
> I still think that this change was a good idea. I'm sorry if this broke one of your existing recipes, but we're trying to make this easier to use going forward, so that's a trade-off I'm willing to accept.
> 
> You can just archive the recipe and create a copy of it with a different serving size and unit. This will leave your existing diary entries unaffected and fix this issue going forward.
> 
> To clear up the confusion, here are some examples of what to enter into the serving size field in the diary when logging a recipe:
> 
>     * If the recipe unit is `cookies` and the recipe serving size is `20` (i.e. the recipe makes 20 cookies), enter the number of cookies you ate.
> 
>     * If the recipe unit is `servings` and the recipe serving size is `4` (i.e. the recipe makes 4 servings), enter the number of servings you ate.
> 
>     * If the recipe unit is `cake` and the recipe serving size is `1` (i.e. the recipe makes 1 cake), enter the share of the cake you ate, e.g. `0.333`.

I really like that suggestion:

I have the following problem and wanted to post a new enhancement, but found this, so I add it here.

I usually mix my own cereals. So I add 650g of product 1, 300g of product 2 [...] and get a large bowl of 1300g cereals. My usual serving size is 150g of that mixture as 1 serving.

for that it would be great to have another new field:
total amount
total amount unit
[new] portion amount

all added products will be sum up to the total amount, 1 portion is the sum of all products divided by (total amount divided by portion amount)

Currently I calculate the added product down to add to 150g for one serving, so if I choose to add that to my diary 1 or 2 servings without to memorize how many grams 1 portion is or how the total amount matches. So the suggestion of adding 0.25 "portion" sizes today can change by every new mixture I do: I don't want to memorize that - it should been handled within the app itself.

so if I add 1000g of product 1 (10g sugar/100g) and 500g of product 2 (20g sugar/100g) and give the total amount of 1500g and a portion size of 150g and add 1 portion of that to my diary I should get added 30g of sugar.

BUT I dont want to get the total amount calculated automatically. If I put 1L of cherry juice, 3L of banana juice together and add water (which I don't add to the recipe) to that I want to declare the amount manually like for 5L and add a portion amount of 200mL so that, the nutrition facts are calculated on the products I added, and the fraction of what is in my portion is only based on the total amount vs. the portion amount. Same for like stuff like juice concentrates, where I add 1L of juice to get like 700mL of concentrate to drink with 150mL portions.

so: yes a new field to make real potion sizes without calculating that by my own would be really great.

**Comment by EmilJunker** [comment]
@Tinsus I don't really understand your request. You can already do that with the current serving size and unit fields.

Step 1: Make a recipe consisting of 1L cherry juice (with say 150g sugar per liter) and 3L banana juice (with say 100g sugar per liter). The total amount of sugar in this recipe would then be 450g.

Step 2: Set the recipe serving size to 5000 and the serving unit to mL (i.e. the total amount is 5000mL or 5L because you also add water).

Step 3: Add the recipe to the diary and enter a serving size of 250mL (which would be 1/20 of the total amount). 

You will see that the amount of sugar in this diary entry will be 22.5g which is of course 1/20 of 450g. Everything is correct and just how you want it.

So what exactly is your request? Do you just want a field to note down the default serving size (e.g. the 250mL in the example above)? If so, you can use the notes field for that.
