### ISSUE TITLE
Body stats can't be activated using German language

### ISSUE THREAD

**Issue by daswasichwillbistdu** [davidhealey/waistline#682]
I'm using Waistline 3.5.2 on Android 13 with my Samsung Galaxy A51. Whenever the language in Waistline is set to German I can't activate or deactivate Body Stats in the settings menu. I tried adding waist circumference to my diary and it didn't work. Only when I changed the language to English I could activate waist circumference. When I changed the language back to German waist circumference stayed active in the diary view but it wasn't marked as active in "Settings"->"Body Stats". Also I couldn't activate or deactivate it until I switched back to the English view of the app interface again. In the German view the button "Add Field" in "Settings"->"Body Stats" is missing as well. At the moment I'm using Waistline in English to circumvent this problem.

**Comment by EmilJunker** [comment]
This feature is quite new, so the German translation strings for the UI aren't yet included in the app. In theory, it should fall back to the English strings if that happens, but it looks like this doesn't work. I may investigate this tomorrow if I find the time to do so.

Anyway, this should be fixed in the next release, provided that the Crowdin branch is merged before that.
