### ISSUE TITLE
First use, user experience and guide

### ISSUE THREAD

**Issue by chk1** [davidhealey/waistline#73]
Thanks a lot for this great app :)

I just started using and exploring this app and noticed a few things I found a little confusing on first use:

* On first start you are dropped into the User Guide, there's no visual indication that there are more pages. I think it would be helpful to add a little note at the end, for example "*Swipe left to read the next page*" (or a chapter index list?) - I can probably do a small PR myself later if that's ok
* It took me a little to figure out where to add my current weight. It's not mentioned in the User Guide as far as I can tell. I think adding small screenshots occasionally through the Guide, or the icon where a feature has a distinct icon (like the scale icon), can be helpful for a first time user.
* Going through all the Goals settings page by page is a bit tedious, a tabbed view may be more pleasant and/or a view that can be swiped left and right.

(using 2.3.3 from F-Droid)

**Comment by davidhealey** [comment]
Hi,

Thanks for your feedback. The idea of some kind of swipe indicator I like. 
Current weight is added in the diary by tapping the scales, I thought this was in the user guide...
The goals screen was intended to be a single page originally but people kept asking for more features so I just added more pages because it was simpler. Combining all the pages into a new tabbed or swipeable setup won't be a trivial task.

**Comment by davidhealey** [comment]
I've added some text at the bottom of the user guide pages now to inform users to swipe to continue.

**Comment by chk1** [comment]
Hey, thanks for the quick reply and fix :)

About the points, I understand if it takes a lot of work, and nutrient goals aren't changed that often I guess.
