### ISSUE TITLE
Automatic Calorie Calculation

### ISSUE THREAD

**Issue by lucamilone** [davidhealey/waistline#774]
Today I installed this app for the first time and found no way to enter my personal parameters (age, height, weight, gender, etc.) in order to be able to calculate my daily calorie requirements automatically.
Based on the current weight, target weight, and amount of daily physical activity (and other parameters used in more advanced calculations) provided by each user, there would need to be a function that calculates the amount of calories needed to meet the most common scenarios: normal-calorie diet, weight loss and weight gain.
In my opinion, this is an important basic functionality for the proper functioning of such an application, because over time users will update their current weight but the calories will not update automatically and this will lead to various problems.

**Comment by davidhealey** [comment]
There is no calculator in Waistline. You can find plenty of calculators online for this and use the result to set your goals within Waistline.

However this is on the todo list and there is a mostly functional tdee calculator within Waistline's source code but it's not enabled on the front end because I never got around to finishing it.
