### ISSUE TITLE
Feature Request: Meal as single item to Diary with option to change weight

### ISSUE THREAD

**Issue by PWRollo** [davidhealey/waistline#777]
Hi together,

first: great app!

I would really appreciate a function where a meal is a single item rather than transferring all the individual items it contains to the diary. The weight of the meal could be the sum of the individual items, so you could easily change it in the diary.
This way you could cook a meal for more than one person and only enter your own quantity in the diary.

Best regards

**Comment by EmilJunker** [comment]
For the use case you are describing, you can create a recipe instead of a meal.

If you add a recipe to the diary, it shows up as a single entry and you can enter the quantity in the unit of the recipe (which you can choose freely when creating the recipe). For example, you can make a recipe for 4 bowls and then enter 1 bowl in the diary to get one quarter of the nutrients.
