### ISSUE TITLE
no results and no prompting when scanning or looking for products. 

### ISSUE THREAD

**Issue by m4ri0g** [davidhealey/waistline#850]
when I scan a product or look for a name on the app.. i sometimes get no coinciding results or something similar instead of asking me if i want to add it to the open food database. 

i looked the product i scanned and it is on the open food database but the app is telling me nothing is coinciding. 

this is the product i am scanning: https://world.openfoodfacts.org/product/0052000328660/fruit-punch-gatorade

**Comment by EmilJunker** [comment]
The Open Food Facts servers appear to be having issues at the moment. They are very slow to respond to requests, see https://status.openfoodfacts.org. Unfortunately, this is happening quite frequently these days.

Because of this, Waistline is running into a timeout and cannot find the product you are scanning. For the same reason, it also doesn't give you the option to upload the product, because it doesn't know whether the product already exists or not.

There is not much we can do to address this problem, other than maybe extend the timeout or improve some of the error messages shown in the app.

**Comment by m4ri0g** [comment]
a more meaningful error message could help.. indeed! thank you
