### ISSUE TITLE
Database corrupted/deleted after deleting a single diary entry

### ISSUE THREAD

**Issue by storkk** [davidhealey/waistline#852]
In the diary view, I long-pressed an entry in order to delete it, received the dialog box asking if I am sure, clicked yes. Nothing appeared to happen (dialog closed but the entry didn't disappear). I closed Waistline, then re-opened and it appears that my entire database (diary, foods, etc.) is empty. Attempting to export also gives a basic skeleton json with zero entries. Goals and tracked nutrients don't seem to have been lost, but all foods, meals, recipes and diary entries over the past 2 years.

Version: 3.8.0 from F-Droid
Android 14
Nothing Phone (1) fully up to date.

**Comment by EmilJunker** [comment]
Foods and diary entries are stored in indexeddb while settings and goals are stored in localstorage. So if we assume that the indexeddb database got corrupted and cleared due to some error, it makes sense that the settings and goals remain unaffected.

Unfortunately, there is nothing we can do to prevent something like this. It has happened in the past (if you look trough the list of issues you should find some similar ones) and it will probably continue to happen once in a while.

Did you have the automatic backup enabled? Then you can restore your database from one of the json backup files. Otherwise, I'm afraid you are out of luck.

**Comment by storkk** [comment]
Hi EmilJunker. I had assumed my data was gone. I took the time to report in order to make it more feasible to track down "some error" that ends with the database getting "corrupted and cleared". 

If this is a known thing that will happen occasionally, and there is no intention of attempting to find the root cause or fixing it, it might be worth stating that somewhere on the main page, or defaulting automatic backups to on, and perhaps just keeping the last few.

**Comment by EmilJunker** [comment]
> If this is a known thing that will happen occasionally, and there is no intention of attempting to find the root cause or fixing it

We have a basic idea what the root cause is: It happens when the Android WebView decides to clear the applications indexeddb ... for reasons known only to itself. But this is not something expected to happen regularly or to a large number of users. It's _extremely_ rare (sorry that it hit you this time). 

> defaulting automatic backups to on, and perhaps just keeping the last few

We already do that. The auto backup has been enabled by default for new users ever since version 3.7 released a year ago. And we keep the backups from the last seven days.

**Comment by storkk** [comment]
OK. I suppose then that the only solution would be to migrate away from indexeddb which can be tampered with by Android WebView and to SQLite or something. Anyway, thanks for your reply - I guess this can now be closed.
